core/urls.py
from django.urls import path


from . import views
from .feeds import LatestPostsFeed

# application namespace, allows urls to be organized by apps
app_name = 'core'

urlpatterns = [
    # portfolio homepage pattern
    path('', views.home, name='home'),

    # post patterns
    path('post/', views.post_list, name='post_list'),
    # path('post/', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('post/tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # Feed
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

cradle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap


from core.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',  namespace='core')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

core/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from ckeditor.fields import RichTextField


class Profile(models.Model):
    avatar_pic = models.ImageField(max_length=255, upload_to="avatar")
    profile_pic = models.ImageField(max_length=255, upload_to="profile")
    name = models.CharField(max_length=25)
    title = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=25)
    caption = models.TextField(max_length=100)
    description = models.TextField(max_length=500)
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

# If you delacre a custom model manager like the one below but you want to keep the objects as default, you have to add objects explicityly in the model
class PublishedManager(models.Manager):
    def get_queryset(self):
        #returns the QuerySet that will be executed. You override this method to include your custom filter in the final QuerySet
        # This returns objects filtered by a publish status
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    # Posts model
    # Posts have status of draft or published and only published posts are displayed publicly
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    banner = models.ImageField(max_length=255, upload_to="banners", null=True, blank=True)
    categories = models.ManyToManyField('Category', related_name='posts', blank=True)
    title = models.CharField(max_length=250)
    # Used for dynamic urls in post-detail view, the slug has unique_for_date parameter to build urls slugs using the publish date and slug. Posts also have unique slugs
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # author defines a many-to-one relationship with posts. When deleted all related posts are deleted due to the SQL standard CASCADE. The name of the reverse relationship from user to post with related_name attr to allow access of related objects easily
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # TODO: Post body, split to Intro, Body and Conclusion Later
    # Add banner Image, offer placeholder dimensions if possible
    intro = RichTextField()
    body = RichTextField()
    conclusion = RichTextField()
    # timezone.now is like a timezone aware version of datetime.now method.
    publish = models.DateTimeField(default=timezone.now)
    # by default, posts create date are started form the moment an instance of post is created
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # first manager declared in a model becomes the default manager, you can use the Meta attr default_manager_name to specify a different manager
    # retreives using Post.objects.all()
    objects = models.Manager() # The default manager of every model that retrieves all objects in the database
    # retreives using Post.published.all()
    published = PublishedManager() # Our custom manager to retreive all posts with published status
    tags = TaggableManager() # taggable manager to add tags to this model

    class Meta:
        '''order by published date from latest'''
        ordering = ('-publish',)
        

    def __str__(self):
        return self.title

    #convention in Django is to add a get_absolute_url() method to the model that returns the canonical URL for the object.
    def get_absolute_url(self):
        return reverse('core:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


# Comment System
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

class Suggest(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='newsletter', null=True)
    suggestion = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.suggestion


class Contact(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    message = models.TextField(null=True, blank=True)
    service = models.CharField(max_length=80)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)



class Testimonial(models.Model):
    name = models.CharField(max_length=80)
    testimony = models.TextField(max_length=150)
    image = models.ImageField(max_length=255, upload_to="testimonies", null=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

    
    class Meta:
        ordering = ('-created',)

core/forms.py
from django import forms


from .models import Comment, Suggest, Contact

# ModelForm
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


# ModelForm
class SuggestForm(forms.ModelForm):
    class Meta:
        model = Suggest
        exclude = ('created', 'post')

        widgets = {
            'suggestion': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'phone', 'email', 'message', 'service')

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': "Whats your name?"}),
            'phone': forms.TextInput(attrs={'placeholder': 'Whats your phone number?',}),
            'email': forms.TextInput(attrs={'placeholder': 'Whats your email address?',}),
            'message': forms.Textarea(attrs={"rows":5, "cols":77, 'placeholder': 'Whats your message?',}),
            'service': forms.TextInput(attrs={'placeholder': 'Whats your service do you want?',}),
        }

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


from .forms import CommentForm, SuggestForm, ContactForm
from .models import Post, Comment, Profile, Suggest, Contact, Testimonial

# Create your views here.

# display homepage
def home(request):
    late_posts = Post.published.annotate(total_comments=Count('comments')).order_by('-total_comments')[:3]
    title = 'Abdi Adan | Portfolio'
    active_profile = Profile.objects.filter(status=True).first()

    testimonial = Testimonial.objects.all()

    contact_details = None
    contact = Contact.objects.all()

    if request.method == 'POST':
        # Contact Me form
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            contact_details = contact_form.save()
            
    else:
        contact_form = CommentForm()


    context = {
                'active_profile': active_profile,
                'title': title,
                'late_posts': late_posts,
                'contact_details': contact_details,
                'contact_form': contact_form,
                'contact': contact,
                'testimonial': testimonial
    }
    return render(request, 'index.html', context)


# display all posts
def post_list(request,  tag_slug=None):
    active_profile = Profile.objects.filter(status=True).first()
    title = 'Abdi Adan | Blog'
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list, 6)
    # get the page GET parameter, which indicates the current page number
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    context = {
                'page': page, 
                'posts': posts,
                'tag': tag,
                'title': title,
                'active_profile': active_profile,
            }
    return render(request, 'blog-list.html', context)



def post_detail(request, year, month, day, post):
    active_profile = Profile.objects.filter(status=True).first()
    title = 'Abdi Adan | Blog'
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    # Comment System on blog-detail
    if request.method == 'POST':
        # Comment form
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            #return HttpResponseRedirect(reverse("post_detail", kwargs={'year':'year', 'month':'month', 'day':'day', 'post':'post'}))
    else:
        comment_form = CommentForm()


    suggestions = Suggest.objects.all()
    new_suggestion = None

    # Suggestion Form on blog-detail
    if request.method == 'POST':
        # Suggestion form
        suggestion_form = SuggestForm(data=request.POST)
        if suggestion_form.is_valid():
            # Create Comment object but don't save to database yet
            new_suggestion = suggestion_form.save(commit=False)
            # Assign the current post to the comment
            new_suggestion.post = post
            # Save the comment to the database
            new_suggestion.save()
            #return HttpResponseRedirect(reverse("post_detail", kwargs={'year':'year', 'month':'month', 'day':'day', 'post':'post'}))
    else:
        suggestion_form = SuggestForm()


    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    


    context = {
                'suggestion_form': suggestion_form,
                'new_suggestion': new_suggestion,
                'suggestions': suggestions,
                'post': post, 
                'comments': comments, 
                'new_comment': new_comment, 
                'comment_form': comment_form,
                'similar_posts': similar_posts,
                'title': title,
                'active_profile': active_profile,
                
            }
    return render(request, 'blog-detail.html', context)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 6
    template_name = 'blog-list.html'

core/templates/components/banners.html
<!-- development banner -->
<div class="sticky-top w-100 fx  elegant-color txt text-center bantext">
    <div class="text-white">
        <div class="text-white covid text-capitalize text-center cov">Under active development, Stay tuned for updates on features and release dates!</div>
    </div>
</div>


<!-- covid-19 banner -->
<!-- <div class="sticky-top w-100 fx blue-gradient text-center">
    <div class="text-white">
        <div class="py-1 text-white covid text-capitalize text-center cov">The Digital transformation your Business needs during this period of COVID-19, Stay Safe, Stay Connected!</div>
    </div>
</div> -->


<!-- black lives matter banner -->
<!-- <div class="sticky-top w-100 fx elegant-color text-center">
    <div class="text-white">
        <div class="py-1 text-white covid text-capitalize text-center cov">To be silent is to stand for, we stand against racism and injustice, black lives matter!</div>
    </div>
</div> -->

core/templates/components/footer.html
    <!-- footer area -->
    <div class="curved-div">
        <div class="curved-div">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,288L30,293.3C60,299,120,309,180,309.3C240,309,300,299,360,245.3C420,192,480,96,540,96C600,96,660,192,720,197.3C780,203,840,117,900,69.3C960,21,1020,11,1080,42.7C1140,75,1200,149,1260,192C1320,235,1380,245,1410,250.7L1440,256L1440,0L1410,0C1380,0,1320,0,1260,0C1200,0,1140,0,1080,0C1020,0,960,0,900,0C840,0,780,0,720,0C660,0,600,0,540,0C480,0,420,0,360,0C300,0,240,0,180,0C120,0,60,0,30,0L0,0Z"></path></svg>
            <footer class="footer-area">
                <div class="container">
                    <div class="">
                        <div class="social text-center">
                            <h5 class="text-uppercase">Follow me</h5>
                            <a href="https://www.linkedin.com/in/abdi-adan-764564176/" target="_blank" ><i class="fab fa-linkedin-in"></i></a>
                            <a href="https://github.com/Abdi-Adan" target="_blank" ><i class="fab fa-github"></i></a>
                            <a href="https://twitter.com/abdi_adan_" target="_blank" ><i class="fab fa-twitter"></i></a>
                            <a href="https://www.instagram.com/_h.a.k.i.m.z_/" target="_blank" ><i class="fab fa-instagram"></i></a>
                            <a href="https://www.facebook.com/abdi.hakim.180" target="_blank" ><i class="fab fa-facebook"></i></a>
                        </div>
                        <div class="copyrights text-center">
                            <p class="para text-white txt">
                                Copyright ©2020 All rights reserved |
                                <a class="txt text-dark"href="#"><span >Abdi Adan</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <!-- end of footer area -->

core/templates/components/navbar.html
{% load static %}


{% block content %}
<!--Navbar -->
    <nav class="navbar_fixed py-3 mt-3 sticky-top txt navbar navbar-expand-lg navbar-dark orange">
        <div class="container">
            <ul class="navbar-nav mr-auto nav-flex-icons">
                <li class="nav-item avatar">
                  <a class="nav-link p-0" href="#">
                    <img src="{% static 'img/pro.png' %}" class="rounded-circle z-depth-0"
                      alt="avatar image" height="50">
                  </a>
                </li>
                
            </ul>
            <a class="pl-3 mr-auto navbar-brand brand pt-2 txt" href="">Portfolio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
            aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-333">

                <ul class="navbar-nav ml-auto align-items-center">
                    <li class="nav-item">
                        <a class="nav-link items" href="{% url 'core:home' %}">Home</a>
                    </li>
                    {% if title == 'Abdi Adan | Portfolio' %}
                    <li class="nav-item">
                        <a class="nav-link items" href="#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link items" href="#why">Why me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link items" href="#projects">Projects</a>
                    </li>
                    {% if testimonial %}
                    <li class="nav-item">
                        <a class="nav-link items" href="#testimonials">Testimonials</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link items" href="{% url 'core:post_list' %}">Blog</a>
                    </li>
                    {% if title == 'Abdi Adan | Portfolio' %}
                    <li class="nav-item mx-2">
                        <div class="btn-submit">
                            <a href="#contact">
                                <button type="button" class="round text-capitalize text-white btn btn-md btn-outline-white float-right">Contact</button>
                            </a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!--/.Navbar -->

{% endblock %}