core/urls.py
from django.urls import path


from . import views
from .feeds import LatestPostsFeed

# application namespace, allows urls to be organized by apps
app_name = 'core'

urlpatterns = [
    # portfolio homepage pattern
    path('', views.home, name='home'),

    # post patterns
    path('post/', views.post_list, name='post_list'),
    # path('post/', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('post/tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # Feed
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

cradle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap


from core.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',  namespace='core')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

core/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from ckeditor.fields import RichTextField


class Profile(models.Model):
    avatar_pic = models.ImageField(max_length=255, upload_to="avatar")
    profile_pic = models.ImageField(max_length=255, upload_to="profile")
    name = models.CharField(max_length=25)
    title = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=25)
    caption = models.TextField(max_length=100)
    description = models.TextField(max_length=500)
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

# If you delacre a custom model manager like the one below but you want to keep the objects as default, you have to add objects explicityly in the model
class PublishedManager(models.Manager):
    def get_queryset(self):
        #returns the QuerySet that will be executed. You override this method to include your custom filter in the final QuerySet
        # This returns objects filtered by a publish status
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    # Posts model
    # Posts have status of draft or published and only published posts are displayed publicly
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    banner = models.ImageField(max_length=255, upload_to="banners", null=True, blank=True)
    categories = models.ManyToManyField('Category', related_name='posts', blank=True)
    title = models.CharField(max_length=250)
    # Used for dynamic urls in post-detail view, the slug has unique_for_date parameter to build urls slugs using the publish date and slug. Posts also have unique slugs
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # author defines a many-to-one relationship with posts. When deleted all related posts are deleted due to the SQL standard CASCADE. The name of the reverse relationship from user to post with related_name attr to allow access of related objects easily
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # TODO: Post body, split to Intro, Body and Conclusion Later
    # Add banner Image, offer placeholder dimensions if possible
    intro = RichTextField()
    body = RichTextField()
    conclusion = RichTextField()
    # timezone.now is like a timezone aware version of datetime.now method.
    publish = models.DateTimeField(default=timezone.now)
    # by default, posts create date are started form the moment an instance of post is created
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # first manager declared in a model becomes the default manager, you can use the Meta attr default_manager_name to specify a different manager
    # retreives using Post.objects.all()
    objects = models.Manager() # The default manager of every model that retrieves all objects in the database
    # retreives using Post.published.all()
    published = PublishedManager() # Our custom manager to retreive all posts with published status
    tags = TaggableManager() # taggable manager to add tags to this model

    class Meta:
        '''order by published date from latest'''
        ordering = ('-publish',)
        

    def __str__(self):
        return self.title

    #convention in Django is to add a get_absolute_url() method to the model that returns the canonical URL for the object.
    def get_absolute_url(self):
        return reverse('core:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


# Comment System
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

class Suggest(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='newsletter', null=True)
    suggestion = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.suggestion


class Contact(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    message = models.TextField(null=True, blank=True)
    service = models.CharField(max_length=80)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)



class Testimonial(models.Model):
    name = models.CharField(max_length=80)
    testimony = models.TextField(max_length=150)
    image = models.ImageField(max_length=255, upload_to="testimonies", null=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

    
    class Meta:
        ordering = ('-created',)

core/forms.py
from django import forms


from .models import Comment, Suggest, Contact

# ModelForm
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


# ModelForm
class SuggestForm(forms.ModelForm):
    class Meta:
        model = Suggest
        exclude = ('created', 'post')

        widgets = {
            'suggestion': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'phone', 'email', 'message', 'service')

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': "Whats your name?"}),
            'phone': forms.TextInput(attrs={'placeholder': 'Whats your phone number?',}),
            'email': forms.TextInput(attrs={'placeholder': 'Whats your email address?',}),
            'message': forms.Textarea(attrs={"rows":5, "cols":77, 'placeholder': 'Whats your message?',}),
            'service': forms.TextInput(attrs={'placeholder': 'Whats your service do you want?',}),
        }

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


from .forms import CommentForm, SuggestForm, ContactForm
from .models import Post, Comment, Profile, Suggest, Contact, Testimonial

# Create your views here.

# display homepage
def home(request):
    late_posts = Post.published.annotate(total_comments=Count('comments')).order_by('-total_comments')[:3]
    title = 'Abdi Adan | Portfolio'
    active_profile = Profile.objects.filter(status=True).first()

    testimonial = Testimonial.objects.all()

    contact_details = None
    contact = Contact.objects.all()

    if request.method == 'POST':
        # Contact Me form
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            contact_details = contact_form.save()
            
    else:
        contact_form = CommentForm()


    context = {
                'active_profile': active_profile,
                'title': title,
                'late_posts': late_posts,
                'contact_details': contact_details,
                'contact_form': contact_form,
                'contact': contact,
                'testimonial': testimonial
    }
    return render(request, 'index.html', context)


# display all posts
def post_list(request,  tag_slug=None):
    active_profile = Profile.objects.filter(status=True).first()
    title = 'Abdi Adan | Blog'
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list, 6)
    # get the page GET parameter, which indicates the current page number
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    context = {
                'page': page, 
                'posts': posts,
                'tag': tag,
                'title': title,
                'active_profile': active_profile,
            }
    return render(request, 'blog-list.html', context)



def post_detail(request, year, month, day, post):
    active_profile = Profile.objects.filter(status=True).first()
    title = 'Abdi Adan | Blog'
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    # Comment System on blog-detail
    if request.method == 'POST':
        # Comment form
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            #return HttpResponseRedirect(reverse("post_detail", kwargs={'year':'year', 'month':'month', 'day':'day', 'post':'post'}))
    else:
        comment_form = CommentForm()


    suggestions = Suggest.objects.all()
    new_suggestion = None

    # Suggestion Form on blog-detail
    if request.method == 'POST':
        # Suggestion form
        suggestion_form = SuggestForm(data=request.POST)
        if suggestion_form.is_valid():
            # Create Comment object but don't save to database yet
            new_suggestion = suggestion_form.save(commit=False)
            # Assign the current post to the comment
            new_suggestion.post = post
            # Save the comment to the database
            new_suggestion.save()
            #return HttpResponseRedirect(reverse("post_detail", kwargs={'year':'year', 'month':'month', 'day':'day', 'post':'post'}))
    else:
        suggestion_form = SuggestForm()


    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    


    context = {
                'suggestion_form': suggestion_form,
                'new_suggestion': new_suggestion,
                'suggestions': suggestions,
                'post': post, 
                'comments': comments, 
                'new_comment': new_comment, 
                'comment_form': comment_form,
                'similar_posts': similar_posts,
                'title': title,
                'active_profile': active_profile,
                
            }
    return render(request, 'blog-detail.html', context)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 6
    template_name = 'blog-list.html'

core/templates/base.html
{% load static %}

{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %} {{ title }} {% endblock %}</title>
    
        <!-- favicon -->
        <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" sizes="64x64">
    
        <!-- Import Bootstrap Grid -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap-grid.min.css">
    
        <!-- Import Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    
        <!-- mdbootstrap css cdn -->
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
    
    
        <!--  Magnific Popup css file  -->
        <link rel="stylesheet" href="{% static 'vendor/Magnific-Popup/dist/magnific-popup.css' %}">
    
    
        <!--  Owl-carousel css file  -->
        <link rel="stylesheet" href="{% static 'vendor/owl-carousel/css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/owl-carousel/css/owl.theme.default.min.css' %}">
    
    
        <!--  custom css file  -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
        <!--  Responsive css file  -->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <!-- fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Varela+Round&display=swap" rel="stylesheet">
    
    </head>
<body>
    {% include "components/banners.html" %}
    {% include "components/navbar.html" %}

    
    {% block content %}

    {% endblock %}



    {% include "components/footer.html" %}

    <!-- side hover social icons -->
    <div class="social-icons social-menu d-none d-lg-block">
        <ul>
            <li class="p-2"><a href="https://www.linkedin.com/in/abdi-adan-764564176/" target="_blank" class="si btn-lg btn-li" type="button" role="button"><i class="fab fa-linkedin-in fa-2x"></i></a></li>
            <li class="p-2"><a href="https://github.com/Abdi-Adan"  target="_blank" class="si btn-lg btn-git" type="button" role="button"><i class="fab fa-github"></i></a></li>
            <li class="p-2"><a href="https://twitter.com/abdi_adan_" target="_blank"  class="si btn-lg btn-tw" type="button" role="button"><i class="fab fa-twitter"></i></a></li>
            <li class="p-2"><a href="https://www.instagram.com/_h.a.k.i.m.z_/"  target="_blank" class="si inst btn-lg btn-ins" type="button" role="button"><i class="fab fa-instagram"></i></a></li>
            <li class="p-2"><a href="https://www.facebook.com/abdi.hakim.180"  target="_blank" class="si btn-lg btn-li" type="button" role="button"><i class="fab fa-facebook"></i></a></li>
        </ul>
    </div>
    <!-- end of side hover social icons -->



    <!-- scroll to top button -->
    <button id="to-top">
        <i class="fab fa-fly fa-3x"></i>
    </button>
    <!-- end of scroll to top button -->



    <!-- to top js -->
    <script>
        const toTop = document.querySelector("#to-top");
        toTop.addEventListener("click", function() {
            window.scrollTo({
                top: 0,
                left: 0,
                behavior: "smooth",
            });
        });
    </script>
    <!-- end of to top js -->

    <!-- mdbootstrap cdn scripts -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/js/mdb.min.js"></script>




    <!--  Jquery js file  -->
    <!-- <script src="{% static 'js/jquery.3.4.1.js' %}"></script> -->

    <!--  Bootstrap js file  -->
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->

    <!--  isotope js library  -->
    <script src="{% static 'vendor/isotope/isotope.min.js' %}"></script>

    <!--  Magnific popup script file  -->
    <script src="{% static 'vendor/Magnific-Popup/dist/jquery.magnific-popup.min.js' %}"></script>

    <!--  Owl-carousel js file  -->
    <script src="{% static 'vendor/owl-carousel/js/owl.carousel.min.js' %}"></script>

    <!--  custom js file  -->
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

core/templates/blog-list.html
{% extends "base.html" %}

{% load static %}

{% load blog_tags %}

<title>{% block title %} {{ title }} {% endblock %}</title>


{% block content %}
  <br>
    <div class="container pt-2 mt-2">
      <!--Main layout-->
      <main class="pt-5">
        <div class="container">
          <!--Section: Post-->
          <section class="mt-3">
            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-md-9">
                <!--Blog list heading-->
                <div class="card wow fadeIn h-100 orange">
                  <div class="">
                    <div class="subscribe">
                      <div class="row">
                        <div class="col-lg-12 text-center subscribe-title">
                          <h4 class="text-uppercase text-white mt-5 txt">
                            Personal Blog
                          </h4>
                          <p class="text-light font-weight-bold">
                            <p class="para text-white my-3 txt">I've written {% total_posts %} articles so far.</p>
                          </p>
                          <p class="para text-white my-3 mx-3 txt">
                            In my blog posts listed below, I mostly write about tech related topics, my passion projects and some are basically a series of blueprint articles to help you do certain projects that you might be intrested in
                          </p>
                          
                          <p class="text-white txt">
                            <a class="text-white" href="{% url "core:post_feed" %}">Subscribe to my RSS feed</a>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!--/.end of Blog list heading-->
              </div>
              <!--Grid column-->

              
              <!--Grid column-->
              <div class="col-md-3">
                <div class="card mb-4 text-center h-100 wow fadeIn">
                  <!--Card content-->
                  <div class="card-body">
                    <img id="profile-pic" class="av-main" src="{% static 'img/pro.png' %}" alt="">
                    <p class="font-weight-bold mt-1 txt">Hi, I'm {{ active_profile.name }}</p>
                    <p class="font-weight-bold txt">
                      <a class="text-black mr-1"><i class="fas fa-envelope-open-text"></i></a>
                      {{ active_profile.email }}
                    </p>
                  </div>
                </div>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </section>
          <!--Section: Post-->
        </div>
      </main>
      <!--Main layout-->
    </div>

        <!-- post list section -->
        <section id="articles" class="viewport">
          <div class="container ">
              <section class="blogs">
                  <div class="container">
                    <div class="mb-3">
                      {% if tag %}
                        <h4>Posts tagged with "{{ tag.name }}"</h4>
                      {% endif %}
                    </div>
                    
                    <div class="row">
                        {% for post in posts %}
                            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                                <div class="card card-body p-2 h-100 post">
                                    <div class="our-project mx-1">
                                        <div class="img img-wrapper">
                                      {% if post.banner %}
                                      <!--Banner Image-->
                                      <div class="img img-wrapper">
                                            <a class="">
                                                <img src="{{ post.banner }}" alt="{{ post.title }}" class="img-fluid">
                                            </a>
                                      </div>
                                      <!--/.Banner Image-->
                                      {% else %}
                                        <div class="img img-wrapper">
                                            <a class="">
                                                <img src="{% static 'img/blog.png' %}" alt="{{ post.title }}" class="img-fluid">
                                            </a>
                                        </div>
                                      {% endif %}
                                        </div>
                                        <div class="content-wrapper">
                                            <h3 class="title">{{ post.title }}</h3>
                                            <p class="text-capitalize">Published {{ post.publish }} by {{ post.author }}</p>
                                            {% if post.tags.all %}
                                              <P>Tags:
                                                {% for tag in post.tags.all %}
                                                  {{ tag.name }}
                                                  {% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                              </p>
                                            {% else %}
                                              <p class="tags">No tags added</p>
                                            {% endif %}
                                            <p>{{ post.intro|markdown|truncatewords_html:20 }}</p>
                                        </div>
                                        <div class="comments-readmore justify-contents-center align-items-center">
                                            <a href="{{ post.get_absolute_url }}"><button class="text-capitalize text-white btn orange">Read</button></a>
                                            <div class="comments justify-content-center align-items-center">
                                              <span><i class="fas fa-comment-alt"></i></span>
                                                {% with post.comments.count as total_comments %}
                                                  <span class="comment-count">
                                                    {{ total_comments }} comment{{ total_comments|pluralize }}
                                                  </span>
                                                {% endwith %}
                                            </div>
                                            <div class="readmore">
                                                <div class="dot dot1"></div>
                                                <div class="dot dot2"></div>
                                                <div class="dot dot3"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    
                  </div>
                  <div class="mt-5">
                    {% include "pagination.html" with page=posts %}
                  </div>
              </section>
          </div>
      </section>
      <!-- end of post list section -->


{% endblock %}

core/templates/latest_posts.html
{% load blog_tags %}

{% load static %}
    
    
    
    <!-- latest articles section -->
    <section id="articles" class="viewport" style="margin-top: 150px;">
        <div class="container ">
            <section class="blogs">
                <div class="project-title">
                    <h1 class="text-uppercase h3 text-center mb-5">Latest Articles</h1>
                </div>
                <div class="container">
                    <div class="row">
                        {% for post in latest_posts %}
                            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                                <div class="card card-body p-2 h-100 post">
                                    <div class="our-project mx-1">
                                        <div class="img img-wrapper">
                                            {% if post.banner %}
                                                <!--Banner Image-->
                                                <div class="img img-wrapper">
                                                        <a class="">
                                                            <img src="{{ post.banner }}" alt="{{ post.title }}" class="img-fluid">
                                                        </a>
                                                </div>
                                                <!--/.Banner Image-->
                                            {% else %}
                                                <div class="img img-wrapper">
                                                    <a class="">
                                                        <img src="{% static 'img/blog.png' %}" alt="{{ post.title }}" class="img-fluid">
                                                    </a>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="content-wrapper">
                                            <h3 class="title">{{ post.title }}</h3>
                                            <p class="text-capitalize">Published {{ post.publish }} by {{ post.author }}</p>
                                            {% if post.tags.all %}
                                              <P>Tags:
                                                {% for tag in post.tags.all %}
                                                  {{ tag.name }}
                                                  {% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                              </p>
                                            {% else %}
                                              <p class="tags">No tags added</p>
                                            {% endif %}
                                            <p>{{ post.intro|markdown|truncatewords_html:20 }}</p>
                                        </div>
                                        <div class="comments-readmore justify-contents-center align-items-center">
                                            <a href="{{ post.get_absolute_url }}"><button class="text-capitalize text-white btn orange">Read</button></a>
                                            <div class="comments justify-content-center align-items-center">
                                              <span><i class="fas fa-comment-alt"></i></span>
                                                {% with post.comments.count as total_comments %}
                                                  <span class="comment-count">
                                                    {{ total_comments }} comment{{ total_comments|pluralize }}
                                                  </span>
                                                {% endwith %}
                                            </div>
                                            <div class="readmore">
                                                <div class="dot dot1"></div>
                                                <div class="dot dot2"></div>
                                                <div class="dot dot3"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </section>
    <!-- end of latest articles section -->

core/templates/pagination.html
<div class="container pag font-weight-bold">
    <div class="pagination pag">
        <span class="step-links pag">
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}" class="text-dark">Previous</a>
            {% endif %}
    
            <span class="current text-dark">
                Page {{ page.number }} of {{ page.paginator.num_pages }}.
            </span>
    
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}" class="text-dark">Next</a>
            {% endif %}
        </span>
    </div>
</div>